spring:
  application:
    name: vehicule-location
  datasource:
    url: jdbc:mysql://localhost:3306/car_rental
    username: root
    password: 
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
